name: learn-github-actions
on:
  push
  workflow_dispatch
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
      - uses: actions/checkout@v4
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
