name: learn-github-actions

on:
  push:
  workflow_dispatch:

jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - run: echo "this is pen"
      - name: Checkout
        uses: actions/checkout@v4
      - run: |
          ls -al
          cd .github/workflows/
          ls -al
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'
      - run: php -v
